[workspace]
members = [
    ".",
    "crates/bunny-api-compute",
    "crates/bunny-api-core",
    "crates/bunny-api-shield",
    "crates/bunny-api-storage",
    "crates/bunny-api-stream",
]
resolver = "2"

[package]
name = "hoppy"
version = "0.1.0"
edition = "2024"
description = "CLI for bunny.net services"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
clap_complete = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
tabled = "0.17"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs"] }
bunny-api-core = { path = "crates/bunny-api-core" }
bunny-api-storage = { path = "crates/bunny-api-storage" }
