mod client;
mod types;

pub use client::ContainersClient;
pub use types::{
    // Applications
    AddApplicationRequest,
    AddApplicationResponse,
    // Container templates
    AddContainerRequest,
    // Endpoints (networking)
    AnycastEndpointRequest,
    // Enums
    AnycastIpProtocolVersion,
    AppListItem,
    Application,
    ApplicationOverview,
    ApplicationStatistics,
    ApplicationStatus,
    AutoscalingSettings,
    CdnEndpointRequest,
    // Container registries
    ContainerConfigSuggestions,
    ContainerEndpoint,
    ContainerEntryPoint,
    ContainerImage,
    ContainerImageTag,
    ContainerInstance,
    ContainerPortMappingRequest,
    ContainerProbe,
    ContainerProbes,
    ContainerRegistry,
    ContainerRegistryRequest,
    ContainerRequest,
    ContainerStatus,
    ContainerTemplate,
    ContainerVolumeMount,
    // Pagination
    CursorList,
    // Volumes
    DeleteAllVolumeInstancesResponse,
    DeleteVolumeInstanceResponse,
    DeploymentStatus,
    DetachVolumeResponse,
    DisplayEndpoint,
    // Overview
    DoubleStatusIndicator,
    EndpointInternalIp,
    EndpointListItem,
    EndpointPortMapping,
    EndpointRequest,
    EndpointStickySession,
    EndpointType,
    EnvironmentVariable,
    EnvironmentVariableSuggestion,
    // Error types
    ErrorDetails,
    GetContainerConfigSuggestionsRequest,
    GetContainerImageDigestRequest,
    Grade,
    Granularity,
    GrpcProbe,
    GrpcProbeRequest,
    HttpGetProbe,
    HttpGetProbeRequest,
    HttpGetProbeResponse,
    ImagePullPolicy,
    ImageTagInfo,
    Int32StatusIndicator,
    ListContainerImageTagsRequest,
    ListContainerImagesRequest,
    // Log forwarding
    ListLogForwardingResponse,
    ListMeta,
    ListVolumesResponse,
    ListVolumesSummary,
    LogForwardingConfiguration,
    LogForwardingRequest,
    LogForwardingType,
    NetworkLimits,
    // Regions & nodes
    OptimalBaseRegionResponse,
    OverviewContainer,
    OverviewPod,
    OverviewRegion,
    PatchApplicationRequest,
    PatchContainerRequest,
    PatchVolumeRequest,
    PodStatus,
    ProblemDetails,
    Protocol,
    Region,
    RegionProvisioningType,
    RegionSettings,
    RegistryCredentials,
    RegistryType,
    RemoveContainerRegistryResult,
    RemoveContainerRegistryStatus,
    RepositorySettings,
    RuntimeType,
    SaveContainerRegistryResult,
    SaveEndpointResponse,
    SavedContainerRegistryStatus,
    SearchPublicContainerImagesRequest,
    StickySessionSettings,
    SyslogFormat,
    TcpSocketProbe,
    TcpSocketProbeRequest,
    UpdateRegionSettingsRequest,
    UpdateVolumeResponse,
    // User limits
    UserLimits,
    ValidationError,
    VolumeInList,
    VolumeInstance,
    VolumeInstanceStatus,
    VolumeMountRequest,
    VolumeRequest,
    VolumeTemplate,
};
