#!/usr/bin/env sh
# run-fixture-coverage-audit.sh — Compare recorded e2e fixtures to the
# Rust structs that deserialize them (and, when available, to the spec
# schema). Writes one combined report at
# hoppy-knowledgebase/research/spec-coverage/fixture-coverage.md.
#
# Fixtures are real API responses captured under fixtures/<domain>/.
# They are an authoritative third source: what the API *actually*
# sends today, distinct from what the spec documents and what hoppy
# models. See [[../research/spec-coverage/README]] for context.

set -eu
cd "$(dirname "$0")/../.."

SCRIPT="hoppy-knowledgebase/scripts/audit-fixture-coverage.sh"
OUT="hoppy-knowledgebase/research/spec-coverage/fixture-coverage.md"

# Each line: title | fixture | jq-prefix | struct-file | struct | spec | schema
# Set spec/schema to "-" to skip spec comparison.
TUPLES=$(cat <<'EOF'
Pull zone (GET)|fixtures/core/pullzone_get.json|.|crates/bunny-net-api/src/core/types.rs|PullZone|specs/core-platform.json|PullZoneModel
Pull zone (with optimizer)|fixtures/core/pullzone_get_with_optimizer.json|.|crates/bunny-net-api/src/core/types.rs|PullZone|specs/core-platform.json|PullZoneModel
Pull zone (with edge rules)|fixtures/core/pullzone_get_with_edgerules.json|.|crates/bunny-net-api/src/core/types.rs|PullZone|specs/core-platform.json|PullZoneModel
Pull zone (magic container)|fixtures/core/pullzone_get_magic_container.json|.|crates/bunny-net-api/src/core/types.rs|PullZone|specs/core-platform.json|PullZoneModel
Pull zone list (first item)|fixtures/core/pullzone_list_paginated.json|.Items[0]|crates/bunny-net-api/src/core/types.rs|PullZone|specs/core-platform.json|PullZoneModel
Storage zone (GET)|fixtures/core/storagezone_get.json|.|crates/bunny-net-api/src/core/types.rs|StorageZone|specs/core-platform.json|StorageZoneModel
Storage zone (CREATE)|fixtures/core/storagezone_create.json|.|crates/bunny-net-api/src/core/types.rs|StorageZone|specs/core-platform.json|StorageZoneModel
DNS zone (GET)|fixtures/core/dnszone_get.json|.|crates/bunny-net-api/src/core/types.rs|DnsZone|specs/core-platform.json|DnsZoneModel
DNS zone (CREATE)|fixtures/core/dnszone_create.json|.|crates/bunny-net-api/src/core/types.rs|DnsZone|specs/core-platform.json|DnsZoneModel
Video library (GET)|fixtures/core/videolibrary_get.json|.|crates/bunny-net-api/src/core/types.rs|VideoLibrary|specs/core-platform.json|VideoLibraryModel
Video library (CREATE)|fixtures/core/videolibrary_create.json|.|crates/bunny-net-api/src/core/types.rs|VideoLibrary|specs/core-platform.json|VideoLibraryModel
Edge script (GET)|fixtures/compute/script_get.json|.|crates/bunny-net-api/src/compute/types.rs|EdgeScript|specs/edge-scripting.json|EdgeScriptModel
Edge script (CREATE)|fixtures/compute/script_create.json|.|crates/bunny-net-api/src/compute/types.rs|EdgeScript|specs/edge-scripting.json|EdgeScriptModel
Shield zone (GET)|fixtures/shield/shield_zone_get.json|.data|crates/bunny-net-api/src/shield/types.rs|ShieldZoneResponse|specs/shield.json|ShieldZoneResponse
Container app (GET)|fixtures/containers/app_get.json|.|crates/bunny-net-api/src/containers/types.rs|ContainerApp|-|-
Container instance (GET)|fixtures/containers/container_get.json|.|crates/bunny-net-api/src/containers/types.rs|ContainerInstance|-|-
Container endpoint (ADD)|fixtures/containers/endpoint_add.json|.|crates/bunny-net-api/src/containers/types.rs|ContainerEndpoint|-|-
EOF
)

{
cat <<'HDR'
---
title: "Fixture coverage audit — recorded API responses vs. structs"
type: research
date: 2026-05-31
tags:
  - audit
  - fixtures
  - spec-coverage
---

# Fixture coverage audit

The OpenAPI specs and the hand-written Rust structs are two sources of
truth. The recorded e2e fixtures under `fixtures/<domain>/` are a third
— and arguably the most authoritative — source: what the bunny.net API
*actually* sends today.

This report runs `audit-fixture-coverage.sh` over every fixture that maps
cleanly to a struct hoppy uses, and pairs the result with the spec when
one is available. Three pair-wise diffs surface different problem
classes:

| Diff | Interpretation |
|---|---|
| fixture − struct | **The real gap**: a field the API sends now that hoppy silently drops. |
| struct − fixture | A field hoppy models but the API didn't send in this recording. Either server-omitted (default), write-only, or a stale struct field. |
| fixture − spec | **Spec lag**: the API ships a field its own OpenAPI doc doesn't list yet. Worth filing upstream. |
| spec − fixture | A documented field the server omitted from this recording (often defaults to absent). |

Generated by `hoppy-knowledgebase/scripts/run-fixture-coverage-audit.sh`.

HDR

echo "$TUPLES" | while IFS='|' read -r title fixture prefix struct_file struct_name spec schema; do
    [ -n "$title" ] || continue
    if [ "$spec" = "-" ] || [ "$schema" = "-" ]; then
        "$SCRIPT" --fixture "$fixture" --jq-prefix "$prefix" \
                  --struct-file "$struct_file" --struct-name "$struct_name" \
                  --title "$title" 2>/dev/null || {
            echo "## $title"; echo
            echo "> **TODO:** audit failed — likely struct or fixture missing."
            echo
            continue
        }
    else
        "$SCRIPT" --fixture "$fixture" --jq-prefix "$prefix" \
                  --struct-file "$struct_file" --struct-name "$struct_name" \
                  --spec "$spec" --schema "$schema" \
                  --title "$title" 2>/dev/null || {
            echo "## $title"; echo
            echo "> **TODO:** audit failed — likely struct or fixture missing."
            echo
            continue
        }
    fi
    echo
done

cat <<'FOOT'

## Takeaways

- **Pull zone fixtures confirm the spec count**: each recorded
  `pullzone_get*.json` has 164 top-level keys — the same number
  `PullZoneModel` declares. There is no "the spec over-states what the
  API returns" effect for pull zones; the 110-field struct gap is real
  on every recording.
- **Shield zone fixture is wrapped in `data`**: handled here via the
  `.data` jq prefix. The bare struct/fixture comparison still suggests
  most "casing mismatches" reported in the spec audit are real (the
  Shield API uses camelCase end-to-end).
- **Container app fixtures have no spec to diff against**, matching
  the `container-app.md` TODO. The fixture-vs-struct diff stands in for
  spec coverage here until a spec lands.
- **Spec lag is not the dominant problem.** Where the spec and the
  fixture both exist, `fixture − spec` is small or zero. The struct
  is the lagging artifact — exactly the finding the dogfooding round
  surfaced.
FOOT
} > "$OUT"

echo "wrote $OUT" >&2
