#!/usr/bin/env bash
#
# Generate an Obsidian-compatible markdown report from E2E test results.
#
# Usage:
#   bash tools/e2e-report.sh
#
set -euo pipefail

REPORT="hoppy-knowledgebase/e2e-test-report.md"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "Running E2E tests..."

# Run tests and capture output. We use cargo test with --no-fail-fast so we get
# all results even if some tests fail. We tee through a temp file so we can
# both see output live and parse it afterwards.
TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT

cargo test --test 'e2e_*' -- --test-threads=4 2>&1 | tee "$TMPFILE" || true

# Parse results
TOTAL=0
PASSED=0
FAILED=0
FAILED_NAMES=()
PASSED_NAMES=()

while IFS= read -r line; do
    if [[ "$line" =~ ^test\ (.+)\ \.\.\.\ ok$ ]]; then
        PASSED_NAMES+=("${BASH_REMATCH[1]}")
        ((PASSED++)) || true
        ((TOTAL++)) || true
    elif [[ "$line" =~ ^test\ (.+)\ \.\.\.\ FAILED$ ]]; then
        FAILED_NAMES+=("${BASH_REMATCH[1]}")
        ((FAILED++)) || true
        ((TOTAL++)) || true
    fi
done < "$TMPFILE"

# Determine overall status
if [ "$FAILED" -eq 0 ] && [ "$TOTAL" -gt 0 ]; then
    STATUS="pass"
else
    STATUS="fail"
fi

# Generate report
mkdir -p "$(dirname "$REPORT")"

cat > "$REPORT" <<EOF
---
type: test-report
suite: e2e
status: ${STATUS}
total: ${TOTAL}
passed: ${PASSED}
failed: ${FAILED}
date: ${TIMESTAMP}
---

# E2E Test Report

**Date:** ${TIMESTAMP}
**Status:** ${STATUS}
**Total:** ${TOTAL} | **Passed:** ${PASSED} | **Failed:** ${FAILED}

## Results

EOF

# Write passed tests
for name in "${PASSED_NAMES[@]+"${PASSED_NAMES[@]}"}"; do
    echo "- [x] \`${name}\`" >> "$REPORT"
done

# Write failed tests
for name in "${FAILED_NAMES[@]+"${FAILED_NAMES[@]}"}"; do
    echo "- [ ] \`${name}\` **FAILED**" >> "$REPORT"
done

echo "" >> "$REPORT"
echo "---" >> "$REPORT"
echo "*Generated by \`tools/e2e-report.sh\`*" >> "$REPORT"

echo ""
echo "Report written to ${REPORT}"
echo "  Total: ${TOTAL}  Passed: ${PASSED}  Failed: ${FAILED}"
