#!/usr/bin/env bash
#
# Generate an Obsidian-compatible markdown report from E2E test results.
# Output is written to hoppy-knowledgebase/e2e-test-report.md (gitignored).
# Raw cargo test output is saved to hoppy-knowledgebase/e2e-test-output.log.
#
# Usage:
#   bash tools/e2e-report.sh
#
set -euo pipefail

REPORT="hoppy-knowledgebase/e2e-test-report.md"
LOGFILE="hoppy-knowledgebase/e2e-test-output.log"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

mkdir -p "$(dirname "$REPORT")"

echo "Running E2E tests..."

# Run tests and capture output. We use cargo test with --no-fail-fast so we get
# all results even if some tests fail. We tee to a persistent log file so
# failure details survive for post-mortem debugging.
cargo test --test 'e2e_*' -- --test-threads=4 2>&1 | tee "$LOGFILE" || true

# Parse results
TOTAL=0
PASSED=0
FAILED=0
FAILED_NAMES=()
PASSED_NAMES=()

while IFS= read -r line; do
    if [[ "$line" =~ ^test\ (.+)\ \.\.\.\ ok$ ]]; then
        PASSED_NAMES+=("${BASH_REMATCH[1]}")
        ((PASSED++)) || true
        ((TOTAL++)) || true
    elif [[ "$line" =~ ^test\ (.+)\ \.\.\.\ FAILED$ ]]; then
        FAILED_NAMES+=("${BASH_REMATCH[1]}")
        ((FAILED++)) || true
        ((TOTAL++)) || true
    fi
done < "$LOGFILE"

# Determine overall status
if [ "$FAILED" -eq 0 ] && [ "$TOTAL" -gt 0 ]; then
    STATUS="pass"
else
    STATUS="fail"
fi

# Generate report
cat > "$REPORT" <<EOF
---
type: test-report
suite: e2e
status: ${STATUS}
total: ${TOTAL}
passed: ${PASSED}
failed: ${FAILED}
date: ${TIMESTAMP}
---

# E2E Test Report

**Date:** ${TIMESTAMP}
**Status:** ${STATUS}
**Total:** ${TOTAL} | **Passed:** ${PASSED} | **Failed:** ${FAILED}

## Results

EOF

# Write passed tests
for name in "${PASSED_NAMES[@]+"${PASSED_NAMES[@]}"}"; do
    echo "- [x] \`${name}\`" >> "$REPORT"
done

# Write failed tests
for name in "${FAILED_NAMES[@]+"${FAILED_NAMES[@]}"}"; do
    echo "- [ ] \`${name}\` **FAILED**" >> "$REPORT"
done

# Extract and append failure details from cargo test output.
# Cargo delimits per-test failure output with "---- test_name stdout ----" markers.
if [ "${#FAILED_NAMES[@]}" -gt 0 ]; then
    echo "" >> "$REPORT"
    echo "## Failures" >> "$REPORT"

    for name in "${FAILED_NAMES[@]}"; do
        echo "" >> "$REPORT"
        echo "### \`${name}\`" >> "$REPORT"
        echo "" >> "$REPORT"
        echo '```' >> "$REPORT"

        # Extract the block between "---- name stdout ----" and the next "----" or end-of-failures marker
        awk -v test="$name" '
            $0 ~ "^---- " test " stdout ----$" { capture=1; next }
            capture && /^---- .+ stdout ----$/ { exit }
            capture && /^failures:$/ { exit }
            capture { print }
        ' "$LOGFILE" >> "$REPORT"

        echo '```' >> "$REPORT"
    done
fi

echo "" >> "$REPORT"
echo "---" >> "$REPORT"
echo "*Generated by \`tools/e2e-report.sh\`*" >> "$REPORT"

echo ""
echo "Report written to ${REPORT}"
echo "Raw output saved to ${LOGFILE}"
echo "  Total: ${TOTAL}  Passed: ${PASSED}  Failed: ${FAILED}"
